### 1.0 simple query without page parameter
POST {{baseUrl}}/jobinfo/query
Accept: application/json
Content-Type: application/json

{"jobGroupId": 1, "author": "jack"}


### 1.1 simple query without page parameter
POST {{baseUrl}}/jobinfo/query
Accept: application/json
Content-Type: application/json

{
  "jobGroupId": 1,
  "author": "a",
  "pageRequest": {
    "page": 1,
    "pageSize": 10,
    "sort": "id",
    "sortDirection": "DESC"
  }
}








