@startuml
'https://plantuml.com/class-diagram

Iterator <|-- PreorderIterator
Iterator <|-- ArrayIterator
Iterator <|-- ListIterator
Iterator <|-- NullIterator


interface Iterator {
+ Glyph first();
+ Glyph Next();
+ boolean isDone();
+ Glyph currentItem();
}

class PreorderIterator {

}

abstract class Glyph {
  + createIterator();
}

@enduml
